### ISSUE TITLE
Problem signing transactions with sign()

### ISSUE THREAD

**Issue by dydt** [stellar/js-stellar-base#27]
If I try to sign a transaction outside of the `TransactionBuilder`, it fails.  That is, this code:

```
var money_account = new StellarLib.Account("GCEZWKCA5VLDNRLN3RPRJMRZOX3Z6G5CHCGSNFHEYVXM3XOJMDS674JZ", 27);
var transaction = new StellarLib.TransactionBuilder(money_account)
    .addOperation(StellarLib.Operation.payment({
      destination: "GASOCNHNNLYFNMDJYQ3XFMI7BYHIOCFW3GJEOWRPEGK2TDPGTG2E5EDW",
      asset: StellarLib.Asset.native(),
      amount: "40000000"
    }))
    // .addSigner(StellarLib.Keypair.fromSeed(rootSeedString))
    .build();
var signer = StellarLib.Keypair.fromSeed(rootSeedString);
transaction.sign([signer]);
server.submitTransaction(transaction)
  .catch(function (err){
    console.log(err);
  });
```

failed with this error:
```
dydt:workspace diyang$ node client_endpoints_examples.js 

/Users/diyang/workspace/js-stellar-lib/node_modules/stellar-base/lib/transaction.js:82
                    var sig = kp.signDecorated(txHash);
                                 ^
TypeError: Object [object Object] has no method 'signDecorated'
    at /Users/diyang/workspace/js-stellar-lib/node_modules/stellar-base/lib/transaction.js:82:34
    at arrayEach (/Users/diyang/workspace/js-stellar-lib/node_modules/lodash/index.js:1289:13)
    at /Users/diyang/workspace/js-stellar-lib/node_modules/lodash/index.js:3345:13
    at Transaction.sign (/Users/diyang/workspace/js-stellar-lib/node_modules/stellar-base/lib/transaction.js:81:31)
    at Object.<anonymous> (/Users/diyang/workspace/client_endpoints_examples.js:158:13)
    ...
```

But this:
```
var money_account = new StellarLib.Account("GCEZWKCA5VLDNRLN3RPRJMRZOX3Z6G5CHCGSNFHEYVXM3XOJMDS674JZ", 26);
var transaction = new StellarLib.TransactionBuilder(money_account)
    .addOperation(StellarLib.Operation.payment({
      destination: "GASOCNHNNLYFNMDJYQ3XFMI7BYHIOCFW3GJEOWRPEGK2TDPGTG2E5EDW",
      asset: StellarLib.Asset.native(),
      amount: "40000000"
    }))
    .addSigner(StellarLib.Keypair.fromSeed(rootSeedString))
    .build();
// var signer = StellarLib.Keypair.fromSeed(rootSeedString);
// transaction.sign([signer]);
server.submitTransaction(transaction)
  .catch(function (err){
    console.log(err);
  });
``` 

succeeded.

**Comment by bartekn** [comment]
It should be:
```js
transaction.sign(signer);
```
Let's say you have 2 signers:
```js
transaction.sign(signer1, signer2);
```
And in case you have an array of signers:
```js
transaction.sign(...arrayOfSigners);
```
More info [here](https://github.com/lukehoban/es6features#default--rest--spread).

**Comment by dydt** [comment]
Okay, thanks!  In that case, would it be correct to update https://github.com/stellar/js-stellar-base/tree/master/docs#transaction-class, or is
```
var keypair = Keypair.fromSeed('SECRETSEED');
transaction.sign([keypair]);
``` 
okay?

**Comment by bartekn** [comment]
Yes, you're right. I will correct it. And I will also change a comment explaining this method because it's confusing now.
