### ISSUE TITLE
Stellar Base not working in Cloudflare Workers

### ISSUE THREAD

**Issue by tyvdh** [stellar/js-stellar-base#378]
**Describe the bug**
Trying to generate a random keypair but getting an unhelpful error.
```
Uncaught (in promise)
TypeError: "size" argument must be a number
    at assertSize (worker.js:427:11)
    at alloc (worker.js:434:3)
    at Function.../../Library/Caches/.wrangler/wranglerjs-1.11.0/node_modules/buffer/index.js.Buffer.alloc (worker.js:454:10)
    at Object.actualMethods.generate (worker.js:28514:21)
    at generate (worker.js:28495:24)
    at new Keypair (worker.js:25468:47)
    at Function.fromRawEd25519Seed (worker.js:25630:14)
    at Function.random (worker.js:25674:19)
    at handleRequest (worker.js:3217:39)
    at worker.js:3229:56
Uncaught (in response)
TypeError: "size" argument must be a number
```

**What version are you on?**
`4.0.2`

**To Reproduce**
Clone, read and run this repo: https://github.com/tyvdh/wrkrtest.

**Expected behavior**
Cloudflare workers are and have been growing in popularity and we should be able to run our SDKs there if possible. It's not a normal node environment and external resources can be tricky to access so it's possible the js-sdk won't ever really work well but for stuff that's just cryptography it should work fine. Right? Seems either our tree shaking isn't working well or something with environment recognition isn't working as expected.

**Comment by tyvdh** [comment]
Fixed by adding 
```js
externals: {
  'sodium-native': 'sodium-native',
},
```
to the webpack.config.js

Either Cloudflare workers, or webpack, or the `'webworker'` target, or some combination of all three apparently doesn't like sodium-native. By setting it to an external resource which never resolves everything defaults back to tweetnacl.
/shrug
