### ISSUE TITLE
TypeError: Cannot read property 'useTestNetwork' of undefined

### ISSUE THREAD

**Issue by Sam-Devs** [stellar/js-stellar-base#387]
**Describe the bug**
I went through the Stellar Doc and followed [follow-received-payments](https://developers.stellar.org/docs/tutorials/follow-received-payments/) tutorial step by step. I ran the script to make a payment 
```
var StellarBase = require("stellar-base");
StellarBase.Network.useTestNetwork();

var keypair = StellarBase.Keypair.fromSecret(
  "SCU36VV2OYTUMDSSU4EIVX4UUHY3XC7N44VL4IJ26IOG6HVNC7DY5UJO",
);
var account = new StellarBase.Account(keypair.publicKey(), "713226564141056");

var amount = "100";
var transaction = new StellarBase.TransactionBuilder(account)
  .addOperation(
    StellarBase.Operation.createAccount({
      destination: StellarBase.Keypair.random().publicKey(),
      startingBalance: amount,
    }),
  )
  .build();

transaction.sign(keypair);

console.log(transaction.toEnvelope().toXDR().toString("base64"));
```
and it threw this error below
```
StellarBase.Network.useTestNetwork();
                    ^

TypeError: Cannot read property 'useTestNetwork' of undefined
    at Object.<anonymous> (C:\Users\Sam\Documents\Projects\Stellar-Horizon\src\make_payment.js:2:21)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)       
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

**What version are you on?**
"stellar-base": "^4.0.3",

**Expected behavior**
After running this script I expected to see a signed transaction blob

**Additional context**

**Comment by ire-and-curses** [comment]
@Sam-Devs try replacing

```StellarBase.Network.useTestNetwork();```
with
```StellarBase.Networks.TESTNET;```

Looks like the quoted doc might be out of date @Shaptic.

https://stellar.github.io/js-stellar-sdk/js-stellar-base_src_network.js.html

```
/**

 * Contains passphrases for common networks:

 * * `Networks.PUBLIC`: `Public Global Stellar Network ; September 2015`

 * * `Networks.TESTNET`: `Test SDF Network ; September 2015`

 * @type {{PUBLIC: string, TESTNET: string}}

 */

export const Networks = {

  PUBLIC: 'Public Global Stellar Network ; September 2015',

  TESTNET: 'Test SDF Network ; September 2015'

};
```

**Comment by Shaptic** [comment]
I've confirmed that this is a documentation bug rather than an SDK bug. Please refer to stellar/new-docs#338 for the more-accurate example JS code.
